# Generated by Django 3.2.5 on 2021-07-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('fi', 'films'), ('se', 'series'), ('ca', 'cartoons')], default='films', max_length=200),
        ),
    ]
